### PR TITLE
add posibility of disabling hsi triggers

### PR DESCRIPTION
**Pull request by strilov**

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
With the current implementation, when the event period is zero, the FakeHSI process (or module) takes 100% of a CPU during the run.  This is because the implementation effectively becomes a tight loop.

Could the "else" clause have a reasonable sleep time (small enough to be unnoticeable to a human at Stop time but long enough to avoid using lots of CPU)?  maybe 1/4 of a second?

An idea:
```
--- a/plugins/FakeHSIEventGenerator.cpp
+++ b/plugins/FakeHSIEventGenerator.cpp
@@ -212,6 +212,7 @@ FakeHSIEventGenerator::generate_hsievents(std::atomic<bool>& running_flag)
     if (m_trigger_interval_ticks.load() > 0) {
       std::this_thread::sleep_for(std::chrono::microseconds(m_event_period.load()));
     } else {
+      std::this_thread::sleep_for(std::chrono::microseconds(250000));
       continue;
     }
```

**Comment by strilov** [comment]
Hi Kurt. That's a good point. Suggested improvement pushed.

**Review by floriangroetschla — APPROVED** [review]
The most recent fix solves the problem for me

**Review by bieryAtFnal — APPROVED** [review]
Looks good to me.

**Pull request merged**
